syntax = "proto3";

package core;

option go_package = "github.com/fnuritdinov/libs/corepb";;

service CoreService {

  rpc GetCategories(GetCategoriesRequest)
      returns(GetCategoriesResponse);

  rpc GetCategory(GetCategoryRequest)
      returns(CategoryResponse);

  rpc CreateCategory(CreateCategoryRequest)
      returns(CategoryResponse);

  rpc UpdateCategory(UpdateCategoryRequest)
      returns(CategoryResponse);

  rpc DeleteCategory(DeleteCategoryRequest)
      returns(DeleteCategoryResponse);



  rpc GetAuthors(GetAuthorsRequest)
      returns(GetAuthorsResponse);

  rpc GetAuthor(GetAuthorRequest)
      returns(AuthorResponse);

  rpc CreateAuthor(CreateAuthorRequest)
      returns(AuthorResponse);

  rpc UpdateAuthor(UpdateAuthorRequest)
      returns(AuthorResponse);

  rpc DeleteAuthor(DeleteAuthorRequest)
      returns(DeleteAuthorResponse);
}


message CategoryResponse {
  int64 id = 1;
  string name = 2;
  string created_at = 3;
  string updated_at = 4;
}

message GetCategoriesRequest {
}

message GetCategoriesResponse {
  repeated CategoryResponse categories = 1;
}

message GetCategoryRequest {
  int64 category_id = 1;
}

message CreateCategoryRequest {
  string name = 1;
}

message UpdateCategoryRequest {
  int64 category_id = 1;
  string name = 2;
}

message DeleteCategoryRequest {
  int64 category_id = 1;
}

message DeleteCategoryResponse {
  bool success = 1;
  string message = 2;
}


// =========================
// Author
// =========================

message AuthorResponse {
  int64 id = 1;
  string first_name = 2;
  string last_name = 3;
  string biography = 4;
  int64 photo_file_id = 5;
  string created_at = 6;
  string updated_at = 7;
}

message GetAuthorsRequest {
}

message GetAuthorsResponse {
  repeated AuthorResponse authors = 1;
}

message GetAuthorRequest {
  int64 author_id = 1;
}

message CreateAuthorRequest {
  string first_name = 1;
  string last_name = 2;
  string biography = 3;
}

message UpdateAuthorRequest {
  int64 author_id = 1;
  string first_name = 2;
  string last_name = 3;
  string biography = 4;
}

message DeleteAuthorRequest {
  int64 author_id = 1;
}

message DeleteAuthorResponse {
  bool success = 1;
  string message = 2;
}