// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: book/book.proto

package bookpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId      int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PdfFileId       int64                  `protobuf:"varint,5,opt,name=pdf_file_id,json=pdfFileId,proto3" json:"pdf_file_id,omitempty"`
	CoverFileId     int64                  `protobuf:"varint,6,opt,name=cover_file_id,json=coverFileId,proto3" json:"cover_file_id,omitempty"`
	Language        string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	PageCount       int32                  `protobuf:"varint,8,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PublicationYear int32                  `protobuf:"varint,9,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBookRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateBookRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateBookRequest) GetPdfFileId() int64 {
	if x != nil {
		return x.PdfFileId
	}
	return 0
}

func (x *CreateBookRequest) GetCoverFileId() int64 {
	if x != nil {
		return x.CoverFileId
	}
	return 0
}

func (x *CreateBookRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateBookRequest) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *CreateBookRequest) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

type BookResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId      int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PdfFileId       int64                  `protobuf:"varint,6,opt,name=pdf_file_id,json=pdfFileId,proto3" json:"pdf_file_id,omitempty"`
	CoverFileId     int64                  `protobuf:"varint,7,opt,name=cover_file_id,json=coverFileId,proto3" json:"cover_file_id,omitempty"`
	Language        string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	PageCount       int32                  `protobuf:"varint,9,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PublicationYear int32                  `protobuf:"varint,10,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	ViewCount       int32                  `protobuf:"varint,11,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *BookResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *BookResponse) GetPdfFileId() int64 {
	if x != nil {
		return x.PdfFileId
	}
	return 0
}

func (x *BookResponse) GetCoverFileId() int64 {
	if x != nil {
		return x.CoverFileId
	}
	return 0
}

func (x *BookResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BookResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *BookResponse) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

func (x *BookResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *BookResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BookResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateBookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId      int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PdfFileId       int64                  `protobuf:"varint,6,opt,name=pdf_file_id,json=pdfFileId,proto3" json:"pdf_file_id,omitempty"`
	CoverFileId     int64                  `protobuf:"varint,7,opt,name=cover_file_id,json=coverFileId,proto3" json:"cover_file_id,omitempty"`
	Language        string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	PageCount       int32                  `protobuf:"varint,9,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PublicationYear int32                  `protobuf:"varint,10,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBookRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *UpdateBookRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateBookRequest) GetPdfFileId() int64 {
	if x != nil {
		return x.PdfFileId
	}
	return 0
}

func (x *UpdateBookRequest) GetCoverFileId() int64 {
	if x != nil {
		return x.CoverFileId
	}
	return 0
}

func (x *UpdateBookRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateBookRequest) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *UpdateBookRequest) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCategoryBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryBooksRequest) Reset() {
	*x = GetCategoryBooksRequest{}
	mi := &file_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryBooksRequest) ProtoMessage() {}

func (x *GetCategoryBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryBooksRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoryBooksRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookResponse        `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_book_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{6}
}

func (x *GetBooksResponse) GetBooks() []*BookResponse {
	if x != nil {
		return x.Books
	}
	return nil
}

type GetAuthorBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorBooksRequest) Reset() {
	*x = GetAuthorBooksRequest{}
	mi := &file_book_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorBooksRequest) ProtoMessage() {}

func (x *GetAuthorBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorBooksRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuthorBooksRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type GetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_book_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{8}
}

func (x *GetBooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_book_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{9}
}

func (x *GetBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type SearchBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBooksRequest) Reset() {
	*x = SearchBooksRequest{}
	mi := &file_book_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBooksRequest) ProtoMessage() {}

func (x *SearchBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBooksRequest.ProtoReflect.Descriptor instead.
func (*SearchBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{10}
}

func (x *SearchBooksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchBooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchBooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetBooksByParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksByParamsRequest) Reset() {
	*x = GetBooksByParamsRequest{}
	mi := &file_book_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksByParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByParamsRequest) ProtoMessage() {}

func (x *GetBooksByParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByParamsRequest.ProtoReflect.Descriptor instead.
func (*GetBooksByParamsRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{11}
}

func (x *GetBooksByParamsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetBooksByParamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBooksByParamsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_book_book_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{12}
}

func (x *FileResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetBookFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookFileRequest) Reset() {
	*x = GetBookFileRequest{}
	mi := &file_book_book_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookFileRequest) ProtoMessage() {}

func (x *GetBookFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookFileRequest.ProtoReflect.Descriptor instead.
func (*GetBookFileRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{13}
}

func (x *GetBookFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type GetCoverFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoverFileRequest) Reset() {
	*x = GetCoverFileRequest{}
	mi := &file_book_book_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoverFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoverFileRequest) ProtoMessage() {}

func (x *GetCoverFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoverFileRequest.ProtoReflect.Descriptor instead.
func (*GetCoverFileRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{14}
}

func (x *GetCoverFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DownloadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileChunk) Reset() {
	*x = DownloadFileChunk{}
	mi := &file_book_book_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileChunk) ProtoMessage() {}

func (x *DownloadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadFileChunk) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadFileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileName         string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	OriginalFileName string                 `protobuf:"bytes,3,opt,name=original_file_name,json=originalFileName,proto3" json:"original_file_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_book_book_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{16}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileChunk) GetOriginalFileName() string {
	if x != nil {
		return x.OriginalFileName
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_book_book_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_book_book_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\"\xb3\x02\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x1e\n" +
	"\vpdf_file_id\x18\x05 \x01(\x03R\tpdfFileId\x12\"\n" +
	"\rcover_file_id\x18\x06 \x01(\x03R\vcoverFileId\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\b \x01(\x05R\tpageCount\x12)\n" +
	"\x10publication_year\x18\t \x01(\x05R\x0fpublicationYear\"\x9b\x03\n" +
	"\fBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1e\n" +
	"\vpdf_file_id\x18\x06 \x01(\x03R\tpdfFileId\x12\"\n" +
	"\rcover_file_id\x18\a \x01(\x03R\vcoverFileId\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\t \x01(\x05R\tpageCount\x12)\n" +
	"\x10publication_year\x18\n" +
	" \x01(\x05R\x0fpublicationYear\x12\x1d\n" +
	"\n" +
	"view_count\x18\v \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xc3\x02\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1e\n" +
	"\vpdf_file_id\x18\x06 \x01(\x03R\tpdfFileId\x12\"\n" +
	"\rcover_file_id\x18\a \x01(\x03R\vcoverFileId\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\t \x01(\x05R\tpageCount\x12)\n" +
	"\x10publication_year\x18\n" +
	" \x01(\x05R\x0fpublicationYear\",\n" +
	"\x11DeleteBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"H\n" +
	"\x12DeleteBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x17GetCategoryBooksRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"<\n" +
	"\x10GetBooksResponse\x12(\n" +
	"\x05books\x18\x01 \x03(\v2\x12.book.BookResponseR\x05books\"4\n" +
	"\x15GetAuthorBooksRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\"?\n" +
	"\x0fGetBooksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\")\n" +
	"\x0eGetBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"X\n" +
	"\x12SearchBooksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x17GetBooksByParamsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"f\n" +
	"\fFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"-\n" +
	"\x12GetBookFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\".\n" +
	"\x13GetCoverFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\"-\n" +
	"\x11DownloadFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"p\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12,\n" +
	"\x12original_file_name\x18\x03 \x01(\tR\x10originalFileName\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\"H\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x90\a\n" +
	"\vBookService\x129\n" +
	"\n" +
	"CreateBook\x12\x17.book.CreateBookRequest\x1a\x12.book.BookResponse\x129\n" +
	"\n" +
	"UpdateBook\x12\x17.book.UpdateBookRequest\x1a\x12.book.BookResponse\x12?\n" +
	"\n" +
	"DeleteBook\x12\x17.book.DeleteBookRequest\x1a\x18.book.DeleteBookResponse\x12I\n" +
	"\x10GetCategoryBooks\x12\x1d.book.GetCategoryBooksRequest\x1a\x16.book.GetBooksResponse\x12E\n" +
	"\x0eGetAuthorBooks\x12\x1b.book.GetAuthorBooksRequest\x1a\x16.book.GetBooksResponse\x129\n" +
	"\bGetBooks\x12\x15.book.GetBooksRequest\x1a\x16.book.GetBooksResponse\x123\n" +
	"\aGetBook\x12\x14.book.GetBookRequest\x1a\x12.book.BookResponse\x12?\n" +
	"\vSearchBooks\x12\x18.book.SearchBooksRequest\x1a\x16.book.GetBooksResponse\x12I\n" +
	"\x10GetBooksByFilter\x12\x1d.book.GetBooksByParamsRequest\x1a\x16.book.GetBooksResponse\x127\n" +
	"\x0eUploadBookFile\x12\x0f.book.FileChunk\x1a\x12.book.FileResponse(\x01\x128\n" +
	"\x0fUploadCoverFile\x12\x0f.book.FileChunk\x1a\x12.book.FileResponse(\x01\x12B\n" +
	"\vGetBookFile\x12\x18.book.GetBookFileRequest\x1a\x17.book.DownloadFileChunk0\x01\x12D\n" +
	"\fGetCoverFile\x12\x19.book.GetCoverFileRequest\x1a\x17.book.DownloadFileChunk0\x01\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.book.DeleteFileRequest\x1a\x18.book.DeleteFileResponseB,Z*github.com/fnuritdinov/library-libs/bookpbb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_book_book_proto_goTypes = []any{
	(*CreateBookRequest)(nil),       // 0: book.CreateBookRequest
	(*BookResponse)(nil),            // 1: book.BookResponse
	(*UpdateBookRequest)(nil),       // 2: book.UpdateBookRequest
	(*DeleteBookRequest)(nil),       // 3: book.DeleteBookRequest
	(*DeleteBookResponse)(nil),      // 4: book.DeleteBookResponse
	(*GetCategoryBooksRequest)(nil), // 5: book.GetCategoryBooksRequest
	(*GetBooksResponse)(nil),        // 6: book.GetBooksResponse
	(*GetAuthorBooksRequest)(nil),   // 7: book.GetAuthorBooksRequest
	(*GetBooksRequest)(nil),         // 8: book.GetBooksRequest
	(*GetBookRequest)(nil),          // 9: book.GetBookRequest
	(*SearchBooksRequest)(nil),      // 10: book.SearchBooksRequest
	(*GetBooksByParamsRequest)(nil), // 11: book.GetBooksByParamsRequest
	(*FileResponse)(nil),            // 12: book.FileResponse
	(*GetBookFileRequest)(nil),      // 13: book.GetBookFileRequest
	(*GetCoverFileRequest)(nil),     // 14: book.GetCoverFileRequest
	(*DownloadFileChunk)(nil),       // 15: book.DownloadFileChunk
	(*FileChunk)(nil),               // 16: book.FileChunk
	(*DeleteFileRequest)(nil),       // 17: book.DeleteFileRequest
	(*DeleteFileResponse)(nil),      // 18: book.DeleteFileResponse
}
var file_book_book_proto_depIdxs = []int32{
	1,  // 0: book.GetBooksResponse.books:type_name -> book.BookResponse
	0,  // 1: book.BookService.CreateBook:input_type -> book.CreateBookRequest
	2,  // 2: book.BookService.UpdateBook:input_type -> book.UpdateBookRequest
	3,  // 3: book.BookService.DeleteBook:input_type -> book.DeleteBookRequest
	5,  // 4: book.BookService.GetCategoryBooks:input_type -> book.GetCategoryBooksRequest
	7,  // 5: book.BookService.GetAuthorBooks:input_type -> book.GetAuthorBooksRequest
	8,  // 6: book.BookService.GetBooks:input_type -> book.GetBooksRequest
	9,  // 7: book.BookService.GetBook:input_type -> book.GetBookRequest
	10, // 8: book.BookService.SearchBooks:input_type -> book.SearchBooksRequest
	11, // 9: book.BookService.GetBooksByFilter:input_type -> book.GetBooksByParamsRequest
	16, // 10: book.BookService.UploadBookFile:input_type -> book.FileChunk
	16, // 11: book.BookService.UploadCoverFile:input_type -> book.FileChunk
	13, // 12: book.BookService.GetBookFile:input_type -> book.GetBookFileRequest
	14, // 13: book.BookService.GetCoverFile:input_type -> book.GetCoverFileRequest
	17, // 14: book.BookService.DeleteFile:input_type -> book.DeleteFileRequest
	1,  // 15: book.BookService.CreateBook:output_type -> book.BookResponse
	1,  // 16: book.BookService.UpdateBook:output_type -> book.BookResponse
	4,  // 17: book.BookService.DeleteBook:output_type -> book.DeleteBookResponse
	6,  // 18: book.BookService.GetCategoryBooks:output_type -> book.GetBooksResponse
	6,  // 19: book.BookService.GetAuthorBooks:output_type -> book.GetBooksResponse
	6,  // 20: book.BookService.GetBooks:output_type -> book.GetBooksResponse
	1,  // 21: book.BookService.GetBook:output_type -> book.BookResponse
	6,  // 22: book.BookService.SearchBooks:output_type -> book.GetBooksResponse
	6,  // 23: book.BookService.GetBooksByFilter:output_type -> book.GetBooksResponse
	12, // 24: book.BookService.UploadBookFile:output_type -> book.FileResponse
	12, // 25: book.BookService.UploadCoverFile:output_type -> book.FileResponse
	15, // 26: book.BookService.GetBookFile:output_type -> book.DownloadFileChunk
	15, // 27: book.BookService.GetCoverFile:output_type -> book.DownloadFileChunk
	18, // 28: book.BookService.DeleteFile:output_type -> book.DeleteFileResponse
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
