// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: book/book.proto

package bookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookSortField int32

const (
	BookSortField_BOOK_SORT_FIELD_UNSPECIFIED    BookSortField = 0 // => CREATED_AT
	BookSortField_BOOK_SORT_FIELD_CREATED_AT     BookSortField = 1 // "Новинки"
	BookSortField_BOOK_SORT_FIELD_DOWNLOAD_COUNT BookSortField = 2 // "Популярное"
)

// Enum value maps for BookSortField.
var (
	BookSortField_name = map[int32]string{
		0: "BOOK_SORT_FIELD_UNSPECIFIED",
		1: "BOOK_SORT_FIELD_CREATED_AT",
		2: "BOOK_SORT_FIELD_DOWNLOAD_COUNT",
	}
	BookSortField_value = map[string]int32{
		"BOOK_SORT_FIELD_UNSPECIFIED":    0,
		"BOOK_SORT_FIELD_CREATED_AT":     1,
		"BOOK_SORT_FIELD_DOWNLOAD_COUNT": 2,
	}
)

func (x BookSortField) Enum() *BookSortField {
	p := new(BookSortField)
	*p = x
	return p
}

func (x BookSortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookSortField) Descriptor() protoreflect.EnumDescriptor {
	return file_book_book_proto_enumTypes[0].Descriptor()
}

func (BookSortField) Type() protoreflect.EnumType {
	return &file_book_book_proto_enumTypes[0]
}

func (x BookSortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookSortField.Descriptor instead.
func (BookSortField) EnumDescriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId      int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Language        string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	PageCount       int32                  `protobuf:"varint,7,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PublicationYear int32                  `protobuf:"varint,8,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	DownloadCount   int64                  `protobuf:"varint,9,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	CoverUrl        *string                `protobuf:"bytes,13,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"` // для <img src>
	PdfUrl          *string                `protobuf:"bytes,14,opt,name=pdf_url,json=pdfUrl,proto3,oneof" json:"pdf_url,omitempty"`       // прямое скачивание
	IsFavorite      *bool                  `protobuf:"varint,15,opt,name=is_favorite,json=isFavorite,proto3,oneof" json:"is_favorite,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Book) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Book) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Book) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Book) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *Book) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

func (x *Book) GetDownloadCount() int64 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

func (x *Book) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Book) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Book) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Book) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

func (x *Book) GetPdfUrl() string {
	if x != nil && x.PdfUrl != nil {
		return *x.PdfUrl
	}
	return ""
}

func (x *Book) GetIsFavorite() bool {
	if x != nil && x.IsFavorite != nil {
		return *x.IsFavorite
	}
	return false
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateBookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId      int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Language        string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	PageCount       int32                  `protobuf:"varint,6,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PublicationYear int32                  `protobuf:"varint,7,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	PdfKey          *string                `protobuf:"bytes,8,opt,name=pdf_key,json=pdfKey,proto3,oneof" json:"pdf_key,omitempty"` // из UploadFileResponse.key
	CoverKey        *string                `protobuf:"bytes,9,opt,name=cover_key,json=coverKey,proto3,oneof" json:"cover_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBookRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateBookRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateBookRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateBookRequest) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *CreateBookRequest) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

func (x *CreateBookRequest) GetPdfKey() string {
	if x != nil && x.PdfKey != nil {
		return *x.PdfKey
	}
	return ""
}

func (x *CreateBookRequest) GetCoverKey() string {
	if x != nil && x.CoverKey != nil {
		return *x.CoverKey
	}
	return ""
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type GetBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Книги одного автора: author_ids = [7].
	// Поиск по имени автора: gateway сначала находит id в core-сервисе.
	AuthorIds     []int64       `protobuf:"varint,2,rep,packed,name=author_ids,json=authorIds,proto3" json:"author_ids,omitempty"`
	CategoryId    *int64        `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Page          *PageRequest  `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	SortBy        BookSortField `protobuf:"varint,5,opt,name=sort_by,json=sortBy,proto3,enum=book.BookSortField" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *GetBooksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetBooksRequest) GetAuthorIds() []int64 {
	if x != nil {
		return x.AuthorIds
	}
	return nil
}

func (x *GetBooksRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *GetBooksRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetBooksRequest) GetSortBy() BookSortField {
	if x != nil {
		return x.SortBy
	}
	return BookSortField_BOOK_SORT_FIELD_UNSPECIFIED
}

type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *GetBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type UpdateBookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookId          int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title           *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AuthorId        *int64                 `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`
	CategoryId      *int64                 `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Language        *string                `protobuf:"bytes,6,opt,name=language,proto3,oneof" json:"language,omitempty"`
	PageCount       *int32                 `protobuf:"varint,7,opt,name=page_count,json=pageCount,proto3,oneof" json:"page_count,omitempty"`
	PublicationYear *int32                 `protobuf:"varint,8,opt,name=publication_year,json=publicationYear,proto3,oneof" json:"publication_year,omitempty"`
	PdfKey          *string                `protobuf:"bytes,9,opt,name=pdf_key,json=pdfKey,proto3,oneof" json:"pdf_key,omitempty"`
	CoverKey        *string                `protobuf:"bytes,10,opt,name=cover_key,json=coverKey,proto3,oneof" json:"cover_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_book_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *UpdateBookRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateBookRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBookRequest) GetAuthorId() int64 {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return 0
}

func (x *UpdateBookRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateBookRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *UpdateBookRequest) GetPageCount() int32 {
	if x != nil && x.PageCount != nil {
		return *x.PageCount
	}
	return 0
}

func (x *UpdateBookRequest) GetPublicationYear() int32 {
	if x != nil && x.PublicationYear != nil {
		return *x.PublicationYear
	}
	return 0
}

func (x *UpdateBookRequest) GetPdfKey() string {
	if x != nil && x.PdfKey != nil {
		return *x.PdfKey
	}
	return ""
}

func (x *UpdateBookRequest) GetCoverKey() string {
	if x != nil && x.CoverKey != nil {
		return *x.CoverKey
	}
	return ""
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_book_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type IncrementDownloadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementDownloadCountRequest) Reset() {
	*x = IncrementDownloadCountRequest{}
	mi := &file_book_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementDownloadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementDownloadCountRequest) ProtoMessage() {}

func (x *IncrementDownloadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementDownloadCountRequest.ProtoReflect.Descriptor instead.
func (*IncrementDownloadCountRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{8}
}

func (x *IncrementDownloadCountRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type CountBooksByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountBooksByAuthorRequest) Reset() {
	*x = CountBooksByAuthorRequest{}
	mi := &file_book_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountBooksByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountBooksByAuthorRequest) ProtoMessage() {}

func (x *CountBooksByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountBooksByAuthorRequest.ProtoReflect.Descriptor instead.
func (*CountBooksByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{9}
}

func (x *CountBooksByAuthorRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type CountBooksByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountBooksByCategoryRequest) Reset() {
	*x = CountBooksByCategoryRequest{}
	mi := &file_book_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountBooksByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountBooksByCategoryRequest) ProtoMessage() {}

func (x *CountBooksByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountBooksByCategoryRequest.ProtoReflect.Descriptor instead.
func (*CountBooksByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{10}
}

func (x *CountBooksByCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_book_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{11}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_book_book_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{12}
}

func (x *FavoriteRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type GetFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesRequest) Reset() {
	*x = GetFavoritesRequest{}
	mi := &file_book_book_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesRequest) ProtoMessage() {}

func (x *GetFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{13}
}

func (x *GetFavoritesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesResponse) Reset() {
	*x = GetFavoritesResponse{}
	mi := &file_book_book_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesResponse) ProtoMessage() {}

func (x *GetFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesResponse.ProtoReflect.Descriptor instead.
func (*GetFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{14}
}

func (x *GetFavoritesResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_OriginalName
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_book_book_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{15}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetOriginalName() string {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_OriginalName); ok {
			return x.OriginalName
		}
	}
	return ""
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_OriginalName struct {
	OriginalName string `protobuf:"bytes,1,opt,name=original_name,json=originalName,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_OriginalName) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_book_book_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{16}
}

func (x *UploadFileResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xee\x04\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\a \x01(\x05R\tpageCount\x12)\n" +
	"\x10publication_year\x18\b \x01(\x05R\x0fpublicationYear\x12%\n" +
	"\x0edownload_count\x18\t \x01(\x03R\rdownloadCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12 \n" +
	"\tcover_url\x18\r \x01(\tH\x01R\bcoverUrl\x88\x01\x01\x12\x1c\n" +
	"\apdf_url\x18\x0e \x01(\tH\x02R\x06pdfUrl\x88\x01\x01\x12$\n" +
	"\vis_favorite\x18\x0f \x01(\bH\x03R\n" +
	"isFavorite\x88\x01\x01B\r\n" +
	"\v_deleted_atB\f\n" +
	"\n" +
	"_cover_urlB\n" +
	"\n" +
	"\b_pdf_urlB\x0e\n" +
	"\f_is_favorite\";\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xc9\x02\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\x06 \x01(\x05R\tpageCount\x12)\n" +
	"\x10publication_year\x18\a \x01(\x05R\x0fpublicationYear\x12\x1c\n" +
	"\apdf_key\x18\b \x01(\tH\x00R\x06pdfKey\x88\x01\x01\x12 \n" +
	"\tcover_key\x18\t \x01(\tH\x01R\bcoverKey\x88\x01\x01B\n" +
	"\n" +
	"\b_pdf_keyB\f\n" +
	"\n" +
	"_cover_key\")\n" +
	"\x0eGetBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"\xd1\x01\n" +
	"\x0fGetBooksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"author_ids\x18\x02 \x03(\x03R\tauthorIds\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12%\n" +
	"\x04page\x18\x04 \x01(\v2\x11.book.PageRequestR\x04page\x12,\n" +
	"\asort_by\x18\x05 \x01(\x0e2\x13.book.BookSortFieldR\x06sortByB\x0e\n" +
	"\f_category_id\"4\n" +
	"\x10GetBooksResponse\x12 \n" +
	"\x05books\x18\x01 \x03(\v2\n" +
	".book.BookR\x05books\"\xee\x03\n" +
	"\x11UpdateBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x04 \x01(\x03H\x02R\bauthorId\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x05 \x01(\x03H\x03R\n" +
	"categoryId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x06 \x01(\tH\x04R\blanguage\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_count\x18\a \x01(\x05H\x05R\tpageCount\x88\x01\x01\x12.\n" +
	"\x10publication_year\x18\b \x01(\x05H\x06R\x0fpublicationYear\x88\x01\x01\x12\x1c\n" +
	"\apdf_key\x18\t \x01(\tH\aR\x06pdfKey\x88\x01\x01\x12 \n" +
	"\tcover_key\x18\n" +
	" \x01(\tH\bR\bcoverKey\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_author_idB\x0e\n" +
	"\f_category_idB\v\n" +
	"\t_languageB\r\n" +
	"\v_page_countB\x13\n" +
	"\x11_publication_yearB\n" +
	"\n" +
	"\b_pdf_keyB\f\n" +
	"\n" +
	"_cover_key\",\n" +
	"\x11DeleteBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"8\n" +
	"\x1dIncrementDownloadCountRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"8\n" +
	"\x19CountBooksByAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\">\n" +
	"\x1bCountBooksByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"*\n" +
	"\x0fFavoriteRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\"<\n" +
	"\x13GetFavoritesRequest\x12%\n" +
	"\x04page\x18\x01 \x01(\v2\x11.book.PageRequestR\x04page\"8\n" +
	"\x14GetFavoritesResponse\x12 \n" +
	"\x05books\x18\x01 \x03(\v2\n" +
	".book.BookR\x05books\"Z\n" +
	"\x11UploadFileRequest\x12%\n" +
	"\roriginal_name\x18\x01 \x01(\tH\x00R\foriginalName\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"&\n" +
	"\x12UploadFileResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key*t\n" +
	"\rBookSortField\x12\x1f\n" +
	"\x1bBOOK_SORT_FIELD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aBOOK_SORT_FIELD_CREATED_AT\x10\x01\x12\"\n" +
	"\x1eBOOK_SORT_FIELD_DOWNLOAD_COUNT\x10\x022\x96\x06\n" +
	"\vBookService\x121\n" +
	"\n" +
	"CreateBook\x12\x17.book.CreateBookRequest\x1a\n" +
	".book.Book\x12+\n" +
	"\aGetBook\x12\x14.book.GetBookRequest\x1a\n" +
	".book.Book\x129\n" +
	"\bGetBooks\x12\x15.book.GetBooksRequest\x1a\x16.book.GetBooksResponse\x121\n" +
	"\n" +
	"UpdateBook\x12\x17.book.UpdateBookRequest\x1a\n" +
	".book.Book\x12=\n" +
	"\n" +
	"DeleteBook\x12\x17.book.DeleteBookRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x16IncrementDownloadCount\x12#.book.IncrementDownloadCountRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x12CountBooksByAuthor\x12\x1f.book.CountBooksByAuthorRequest\x1a\x13.book.CountResponse\x12N\n" +
	"\x14CountBooksByCategory\x12!.book.CountBooksByCategoryRequest\x1a\x13.book.CountResponse\x12A\n" +
	"\n" +
	"UploadFile\x12\x17.book.UploadFileRequest\x1a\x18.book.UploadFileResponse(\x01\x12<\n" +
	"\vAddFavorite\x12\x15.book.FavoriteRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x0eRemoveFavorite\x12\x15.book.FavoriteRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fGetFavorites\x12\x19.book.GetFavoritesRequest\x1a\x1a.book.GetFavoritesResponseB\tZ\a/bookpbb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_book_book_proto_goTypes = []any{
	(BookSortField)(0),                    // 0: book.BookSortField
	(*Book)(nil),                          // 1: book.Book
	(*PageRequest)(nil),                   // 2: book.PageRequest
	(*CreateBookRequest)(nil),             // 3: book.CreateBookRequest
	(*GetBookRequest)(nil),                // 4: book.GetBookRequest
	(*GetBooksRequest)(nil),               // 5: book.GetBooksRequest
	(*GetBooksResponse)(nil),              // 6: book.GetBooksResponse
	(*UpdateBookRequest)(nil),             // 7: book.UpdateBookRequest
	(*DeleteBookRequest)(nil),             // 8: book.DeleteBookRequest
	(*IncrementDownloadCountRequest)(nil), // 9: book.IncrementDownloadCountRequest
	(*CountBooksByAuthorRequest)(nil),     // 10: book.CountBooksByAuthorRequest
	(*CountBooksByCategoryRequest)(nil),   // 11: book.CountBooksByCategoryRequest
	(*CountResponse)(nil),                 // 12: book.CountResponse
	(*FavoriteRequest)(nil),               // 13: book.FavoriteRequest
	(*GetFavoritesRequest)(nil),           // 14: book.GetFavoritesRequest
	(*GetFavoritesResponse)(nil),          // 15: book.GetFavoritesResponse
	(*UploadFileRequest)(nil),             // 16: book.UploadFileRequest
	(*UploadFileResponse)(nil),            // 17: book.UploadFileResponse
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 19: google.protobuf.Empty
}
var file_book_book_proto_depIdxs = []int32{
	18, // 0: book.Book.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: book.Book.updated_at:type_name -> google.protobuf.Timestamp
	18, // 2: book.Book.deleted_at:type_name -> google.protobuf.Timestamp
	2,  // 3: book.GetBooksRequest.page:type_name -> book.PageRequest
	0,  // 4: book.GetBooksRequest.sort_by:type_name -> book.BookSortField
	1,  // 5: book.GetBooksResponse.books:type_name -> book.Book
	2,  // 6: book.GetFavoritesRequest.page:type_name -> book.PageRequest
	1,  // 7: book.GetFavoritesResponse.books:type_name -> book.Book
	3,  // 8: book.BookService.CreateBook:input_type -> book.CreateBookRequest
	4,  // 9: book.BookService.GetBook:input_type -> book.GetBookRequest
	5,  // 10: book.BookService.GetBooks:input_type -> book.GetBooksRequest
	7,  // 11: book.BookService.UpdateBook:input_type -> book.UpdateBookRequest
	8,  // 12: book.BookService.DeleteBook:input_type -> book.DeleteBookRequest
	9,  // 13: book.BookService.IncrementDownloadCount:input_type -> book.IncrementDownloadCountRequest
	10, // 14: book.BookService.CountBooksByAuthor:input_type -> book.CountBooksByAuthorRequest
	11, // 15: book.BookService.CountBooksByCategory:input_type -> book.CountBooksByCategoryRequest
	16, // 16: book.BookService.UploadFile:input_type -> book.UploadFileRequest
	13, // 17: book.BookService.AddFavorite:input_type -> book.FavoriteRequest
	13, // 18: book.BookService.RemoveFavorite:input_type -> book.FavoriteRequest
	14, // 19: book.BookService.GetFavorites:input_type -> book.GetFavoritesRequest
	1,  // 20: book.BookService.CreateBook:output_type -> book.Book
	1,  // 21: book.BookService.GetBook:output_type -> book.Book
	6,  // 22: book.BookService.GetBooks:output_type -> book.GetBooksResponse
	1,  // 23: book.BookService.UpdateBook:output_type -> book.Book
	19, // 24: book.BookService.DeleteBook:output_type -> google.protobuf.Empty
	19, // 25: book.BookService.IncrementDownloadCount:output_type -> google.protobuf.Empty
	12, // 26: book.BookService.CountBooksByAuthor:output_type -> book.CountResponse
	12, // 27: book.BookService.CountBooksByCategory:output_type -> book.CountResponse
	17, // 28: book.BookService.UploadFile:output_type -> book.UploadFileResponse
	19, // 29: book.BookService.AddFavorite:output_type -> google.protobuf.Empty
	19, // 30: book.BookService.RemoveFavorite:output_type -> google.protobuf.Empty
	15, // 31: book.BookService.GetFavorites:output_type -> book.GetFavoritesResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	file_book_book_proto_msgTypes[0].OneofWrappers = []any{}
	file_book_book_proto_msgTypes[2].OneofWrappers = []any{}
	file_book_book_proto_msgTypes[4].OneofWrappers = []any{}
	file_book_book_proto_msgTypes[6].OneofWrappers = []any{}
	file_book_book_proto_msgTypes[15].OneofWrappers = []any{
		(*UploadFileRequest_OriginalName)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		EnumInfos:         file_book_book_proto_enumTypes,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
